### ISSUE TITLE
More explicit commit messages

### ISSUE THREAD

**Issue by neauoire** [nikitavoloboev/knowledge#19]
I watch the repo and often check the changes, I tend to use your repo as a source of inspiration for things that might interest me, it would be neat if instead of "update" your updates would be the changed files, like "language, zerowaste, cooking, and 2 other".

Just a thought.

**Comment by nikitavoloboev** [comment]
That's a good suggestion. I will look into automating that though because I don't want to spend time crafting commit messages for a repo that is write only, never revert. It's mostly as a way to render my notes into HTML with GitBook. 

But I agree more explicit commit messages would be great. I'll try add it. 🙂

p.s. You probably know about [Alfred My Mind](https://github.com/nikitavoloboev/alfred-my-mind#readme) workflow I wrote. It makes querying the wiki super easy.

**Comment by neauoire** [comment]
Thanks :) Yeah, automated of course.

I know the workflow, but sometimes I'm in bed and on my phone and I just wanna see what new things you've stumbled onto ;)

**Comment by nikitavoloboev** [comment]
Would something like this work?

https://github.com/nikitavoloboev/knowledge/commit/43266519f8f44982824db0ecbfe5482925c73d38

**Comment by neauoire** [comment]
Perfect.

**Comment by neauoire** [comment]
I think it broke? It reverted back to `update`.

**Comment by nikitavoloboev** [comment]
I manually made those commits you saw earlier. If you want to help write a function that will solve #20, I would appreciate it. So I can run it instead of my current 'update' script I run.

**Comment by neauoire** [comment]
I'll have a look :)

**Comment by nikitavoloboev** [comment]
It's done

https://github.com/nikitavoloboev/knowledge/commits/master

Commits now include files that were changed as part of commit msg.

The binary that does it: https://github.com/nikitavoloboev/build-to-learn/blob/master/go/wikiupdate/main.go

Will improve it in a bit, I quite like this approach for automated commits.
